/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javagraph;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;

//Class qui definié l'écran principal
/**
 * écran pricipal
 */
public class HomeScreen extends javax.swing.JFrame {
    
    private Graph graph;
    
    public static HomeScreen hs;
    /**active ville*/
    public void setActiveNodeCategory(String category) {
        this.nodeCategory.setSelectedItem(category);
    }
    /**active route*/
    public void setActiveLinkCategory(String category) {
        this.linkCategory.setSelectedItem(category);
    }

    /**
     * Creates new form HomeScreen
     * @param graph
     */
    public HomeScreen(Graph graph) {
        if (hs != null) return;
        
        this.graph = graph;
        
        GraphPanel gpanel = new GraphPanel(graph);
        getContentPane().add(gpanel);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        setVisible(true);
        
        gpanel.setSize(600, 500);
        
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // To maximize a frame
        
        totalNodes.setText(graph.getNodes().size()+"");
        totalLinks.setText(graph.getLinks().size()+"");
        
        hs = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nodeCategory = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        nodesList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        linkCategory = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        linksList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalNodes = new javax.swing.JLabel();
        totalLinks = new javax.swing.JLabel();
        totalNodes1 = new javax.swing.JLabel();
        totalLinks1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1399, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Graph viewer");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 340, 29));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setText("Sélectionnez la catégoriede nœud");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        nodeCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V", "L", "R" }));
        nodeCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodeCategoryActionPerformed(evt);
            }
        });
        jPanel2.add(nodeCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));

        nodesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Choisir une catégorie" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(nodesList);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, 320));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setText("Sélectionnez la catégorie de lien");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        linkCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "N", "D" }));
        linkCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkCategoryActionPerformed(evt);
            }
        });
        jPanel2.add(linkCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 150, 30));

        linksList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Sélectionner le genre" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(linksList);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 150, 320));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nœuds totaux");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 120, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("nombre total de liens");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 120, 20));
        jPanel2.add(totalNodes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));
        jPanel2.add(totalLinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 20, 20));
        jPanel2.add(totalNodes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 20, 20));
        jPanel2.add(totalLinks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 420, 580));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Voisins direct");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Plus court chemin");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Comparaison");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**clic sur ville x, voisins de x et x coloré*/
    private void nodeCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodeCategoryActionPerformed
        // Verifie quelle catégorie de liens on a chiosi
        String selectedCategory = (String) nodeCategory.getSelectedItem();
        //met tous les lieux au stade inactif
        graph.setAllInActive();
        
        DefaultListModel<String> model = new DefaultListModel<>();
        for(int i = 0; i < graph.getNodes().size(); i++){
            if(graph.getNodes().get(i).getType().equalsIgnoreCase(selectedCategory)) {
                model.addElement(graph.getNodes().get(i).getName());
                // setting selected type active
                graph.getNodes().get(i).setActive();
            }
        }
        nodesList.setModel(model);
        this.repaint();
    }//GEN-LAST:event_nodeCategoryActionPerformed
/**clic sur route x, les deux villes qui relie sont coloré*/
    private void linkCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkCategoryActionPerformed
        // Verifie quelle catégorie de routes on a chiosi
        String selectedType = (String) linkCategory.getSelectedItem();
        // met tous les liens au stade inactif
        graph.setAllInActive();
        
        DefaultListModel<String> model = new DefaultListModel<>();
        for(int i = 0; i < graph.getLinks().size(); i++){
            Link lnk = graph.getLinks().get(i);
            if (lnk.getType().equalsIgnoreCase(selectedType)) {
                model.addElement(graph.getLinks().get(i).getName());
                graph.getLinks().get(i).setActive();
            }
        }
        linksList.setModel(model);
        this.repaint();
    }//GEN-LAST:event_linkCategoryActionPerformed
/**Screen 1*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Verifie quand on clique sur le bouton1 étant celui de l'écran 1, si oui l'affiche
        new Screen1(this.graph);
        Screen1.sc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
/**Screen 2*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Verifie quand on clique sur le bouton2 étant celui de l'écran 2, si oui l'affiche
        new Screen3(this.graph);
        Screen3.sc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
/**Screen 3*/
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Verifie quand on clique sur le bouton3 étant celui de l'écran 3, si oui l'affiche
        new Screen2(this.graph);
        Screen2.sc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox linkCategory;
    private javax.swing.JList<String> linksList;
    private javax.swing.JComboBox nodeCategory;
    private javax.swing.JList<String> nodesList;
    private javax.swing.JLabel totalLinks;
    private javax.swing.JLabel totalLinks1;
    private javax.swing.JLabel totalNodes;
    private javax.swing.JLabel totalNodes1;
    // End of variables declaration//GEN-END:variables
}
