/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javagraph;

import java.awt.Dimension;
import java.awt.Toolkit;
/**
 * écran 2
 */
public class Screen2 extends javax.swing.JFrame {
    
    private Graph graph;
    
    public static Screen2 sc;
    boolean launched = false;
    private Node[] selectedNodes = new Node[2];

    /**
     * Creates new form HomeScreen
     * @param graph
     */
    
    public Screen2(Graph graph) {
        if (sc != null) return;
        
        this.graph = graph;
        
        GraphPanel gpanel = new GraphPanel(graph);
        getContentPane().add(gpanel);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        setVisible(true);
        
        gpanel.setSize(600, 500);
        
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // To maximize a frame
        
        sc = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nodesList2 = new javax.swing.JComboBox();
        are2Distance = new javax.swing.JLabel();
        nodesList1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        leisures1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cities1 = new javax.swing.JLabel();
        restaurants1 = new javax.swing.JLabel();
        leisures2 = new javax.swing.JLabel();
        restaurants2 = new javax.swing.JLabel();
        cities2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1399, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("2-Distance");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 340, 29));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setText("loisirs à 2 distance:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        nodesList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodesList2ActionPerformed(evt);
            }
        });
        for (int i=0; i<graph.getNodes().size(); i++) {
            nodesList2.addItem(graph.getNodes().get(i).getName());
        }
        jPanel2.add(nodesList2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 160, 30));

        are2Distance.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        are2Distance.setText("false");
        jPanel2.add(are2Distance, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 80, 30));

        nodesList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodesList1ActionPerformed(evt);
            }
        });
        for (int i=0; i<graph.getNodes().size(); i++) {
            nodesList1.addItem(graph.getNodes().get(i).getName());
        }
        jPanel2.add(nodesList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setText("ville1");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setText("ville2");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setText("Sont à deux distances:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        leisures1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        leisures1.setText("0");
        jPanel2.add(leisures1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 40, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel7.setText("Restaurant à 2 distance:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel8.setText("Villes à 2 distances:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel9.setText("Restaurant à 2 distance:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel10.setText("loisirs à 2 distance:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel11.setText("Villes à 2 distances:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        cities1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        cities1.setText("0");
        jPanel2.add(cities1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 40, -1));

        restaurants1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        restaurants1.setText("0");
        jPanel2.add(restaurants1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 40, -1));

        leisures2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        leisures2.setText("0");
        jPanel2.add(leisures2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 40, -1));

        restaurants2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        restaurants2.setText("0");
        jPanel2.add(restaurants2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 40, -1));

        cities2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        cities2.setText("0");
        jPanel2.add(cities2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 40, -1));

        jLabel6.setText("/");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel12.setText("/");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel13.setText("Ville la plus ouverte :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel14.setText("Ville la plus gastronomique :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel15.setText("Ville la plus touristique :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel16.setText("/");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 420, 580));

        backBtn.setBackground(new java.awt.Color(204, 204, 204));
        backBtn.setText("Back");
        backBtn.setFocusable(false);
        backBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    /**compare la ville 1 et la ville 2*/
    private void nodesList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodesList2ActionPerformed
        // TODO add your handling code here:
        String selectedNode = (String) nodesList2.getSelectedItem();
        
        graph.setAllInActive();
        
        Node foundNode = Graph.findNode(selectedNode, graph.getNodes());
        this.selectedNodes[0] = foundNode;
        this.selectedNodes[0].setActive();
        foundNode.setActive();
        if (this.selectedNodes[1] != null) {
            this.selectedNodes[1].setActive();
            
            this.cities2.setText(foundNode.totalCitiesAt2Distance()+"");
            this.restaurants2.setText(foundNode.totalRestaurantsAt2Distance()+"");
            this.leisures2.setText(foundNode.totalLeisuresAt2Distance()+"");
            if (this.launched == true && Integer.parseInt(this.cities2.getText()) > Integer.parseInt(this.cities1.getText())){
                this.jLabel6.setText(this.nodesList2.getSelectedItem().toString());
            }else if (this.launched == true && Integer.parseInt(this.cities1.getText()) > Integer.parseInt(this.cities2.getText())){
                this.jLabel6.setText(this.nodesList1.getSelectedItem().toString());
            }else if (this.launched == true && Integer.parseInt(this.cities1.getText()) == Integer.parseInt(this.cities2.getText())){
                this.jLabel6.setText("Egalité");
            }
            if (this.launched == true && Integer.parseInt(this.restaurants2.getText()) > Integer.parseInt(this.restaurants1.getText())){
                this.jLabel16.setText(this.nodesList2.getSelectedItem().toString());
            }else if (this.launched == true && Integer.parseInt(this.restaurants1.getText()) > Integer.parseInt(this.restaurants2.getText())){
                this.jLabel16.setText(this.nodesList1.getSelectedItem().toString());
            }else if (this.launched == true && Integer.parseInt(this.restaurants1.getText()) == Integer.parseInt(this.restaurants2.getText())){
                this.jLabel16.setText("Egalité");
            }
            if (this.launched == true && Integer.parseInt(this.leisures2.getText()) > Integer.parseInt(this.leisures1.getText())){
                this.jLabel12.setText(this.nodesList2.getSelectedItem().toString());
            }else if (this.launched == true && Integer.parseInt(this.leisures1.getText()) > Integer.parseInt(this.leisures2.getText())){
                this.jLabel12.setText(this.nodesList1.getSelectedItem().toString());
            }else if (this.launched == true && Integer.parseInt(this.leisures1.getText()) == Integer.parseInt(this.leisures2.getText())){
                this.jLabel12.setText("Egalité");
            }
            
            
            
            this.launched = true;
        }
        this.repaint();
    }//GEN-LAST:event_nodesList2ActionPerformed
/**retour*/
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HomeScreen.hs.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed
    /**compare la ville 1 et la ville 2*/
    private void nodesList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodesList1ActionPerformed
        
        String selectedNode = (String) nodesList1.getSelectedItem();
        
        graph.setAllInActive();
        
        Node foundNode = Graph.findNode(selectedNode, graph.getNodes());
        this.selectedNodes[1] = foundNode;
        this.selectedNodes[1].setActive();
        if (this.selectedNodes[0] != null) {
            
            this.selectedNodes[0].setActive();
            
            this.are2Distance.setText(foundNode.isAt2Distance(this.selectedNodes[0])+"");
            this.cities1.setText(foundNode.totalCitiesAt2Distance()+"");
            this.restaurants1.setText(foundNode.totalRestaurantsAt2Distance()+"");
            if (this.launched == true && Integer.parseInt(this.cities2.getText()) > Integer.parseInt(this.cities1.getText())){
                this.jLabel6.setText(this.nodesList2.getSelectedItem().toString());
            }else if (this.launched == true && Integer.parseInt(this.cities1.getText()) > Integer.parseInt(this.cities2.getText())){
                this.jLabel6.setText(this.nodesList1.getSelectedItem().toString());
            }else if (this.launched == true && Integer.parseInt(this.cities1.getText()) == Integer.parseInt(this.cities2.getText())){
                this.jLabel6.setText("Egalité");
            }
            if (this.launched == true && Integer.parseInt(this.restaurants2.getText()) > Integer.parseInt(this.restaurants1.getText())){
                this.jLabel16.setText(this.nodesList2.getSelectedItem().toString());
            }else if (this.launched == true && Integer.parseInt(this.restaurants1.getText()) > Integer.parseInt(this.restaurants2.getText())){
                this.jLabel16.setText(this.nodesList1.getSelectedItem().toString());
            }else if (this.launched == true && Integer.parseInt(this.restaurants1.getText()) == Integer.parseInt(this.restaurants2.getText())){
                this.jLabel16.setText("Egalité");
            }
            if (this.launched == true && Integer.parseInt(this.leisures2.getText()) > Integer.parseInt(this.leisures1.getText())){
                this.jLabel12.setText(this.nodesList2.getSelectedItem().toString());
            }else if (this.launched == true && Integer.parseInt(this.leisures1.getText()) > Integer.parseInt(this.leisures2.getText())){
                this.jLabel12.setText(this.nodesList1.getSelectedItem().toString());
            }else if (this.launched == true && Integer.parseInt(this.leisures1.getText()) == Integer.parseInt(this.leisures2.getText())){
                this.jLabel12.setText("Egalité");
            }
            
            
            
            
            this.launched = true;
            
        }
        
        this.repaint();
    }//GEN-LAST:event_nodesList1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel are2Distance;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel cities1;
    private javax.swing.JLabel cities2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel leisures1;
    private javax.swing.JLabel leisures2;
    private javax.swing.JComboBox nodesList1;
    private javax.swing.JComboBox nodesList2;
    private javax.swing.JLabel restaurants1;
    private javax.swing.JLabel restaurants2;
    // End of variables declaration//GEN-END:variables
}
